apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-r1
  labels:
    app: helloworld
    version: r1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: r1
  template:
    metadata:
      labels:
        app: helloworld
        version: r1
    spec:
      containers:
      - name: helloworld
        image: jokercd/helloworld:v1
        ports:
        - containerPort: 6000
        imagePullPolicy: Always
